spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

springbootwebfluxjjwt:
  jjwt:
    secret: ${SPRING_JWT_SECRET}
    expiration: ${SPRING_JWT_EXPIRATION}
  password:
    encoder:
      secret: ${PWD_SECRET_ENCODER}
      iteration: ${ITERATION}
      keylength: ${KEY_LENGTH}
      IV: ${IV}
      salt: ${SALT}